name: tokenai
description: "Token AI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  intl: ^0.19.0
  dio: ^5.8.0+1
  flutter_local_notifications: ^18.0.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.17
  http: ^1.3.0
  google_sign_in: ^6.3.0
  url_launcher: ^6.3.1
  stellar_flutter_sdk: ^1.9.3
  bip39_mnemonic: ^3.0.9
  ed25519_hd_key: ^2.3.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/svg/
    - assets/icons/

